// /shop/financials - manager-only money view.
//
// requirePermission('viewFinancials') is the gate: foreman and tech both resolve to
// false and get redirected to /shop, so nothing below has to redact costs or margin.
//
// The selected period lives in the URL (?preset=&year=&from=&to=) so this stays a
// server component and a period is a shareable link.

import { requirePermission } from '@/lib/auth'
import {
  isRangePreset,
  rangeFor,
  summarize,
  type RangePreset,
} from '@/lib/shop/quickbooks'
import { fetchInvoices } from './_data'
import RangeSelector from './_components/range-selector'
import SummaryCards from './_components/summary-cards'
import InvoiceTable from './_components/invoice-table'
import QuickbooksExport from './_components/quickbooks-export'

export const metadata = { title: 'Financials — NWI Shop' }

// Typed literally rather than with PageProps<'/shop/financials'> because the route
// type map is regenerated by `next dev`; this shape is what that helper resolves to.
interface Props {
  searchParams: Promise<Record<string, string | string[] | undefined>>
}

function first(value: string | string[] | undefined): string | null {
  if (Array.isArray(value)) return value[0] ?? null
  return value ?? null
}

export default async function FinancialsPage({ searchParams }: Props) {
  const { shop } = await requirePermission('viewFinancials')

  const params      = await searchParams
  const currentYear = new Date().getFullYear()

  const presetParam = first(params.preset)
  const preset: RangePreset = isRangePreset(presetParam) ? presetParam : 'ytd'

  const yearParam = Number(first(params.year))
  const year = Number.isInteger(yearParam) && yearParam >= 2000 && yearParam <= currentYear
    ? yearParam
    : currentYear

  const range = rangeFor(preset, year, { from: first(params.from), to: first(params.to) })
  const years = Array.from({ length: 5 }, (_, i) => currentYear - i)

  // Degrades to an empty period with a banner rather than throwing: the shop_* tables
  // may not exist yet in every environment.
  const { invoices, error } = await fetchInvoices(shop.id, range.from, range.to)
  const summary = summarize(invoices, shop)

  return (
    <div className="space-y-6">
      <header>
        <p className="text-xs font-semibold uppercase tracking-widest text-slate-500">
          {shop.business_name}
        </p>
        <h1 className="mt-1 text-2xl font-bold text-slate-900 sm:text-3xl">Financials</h1>
        <p className="mt-1 text-sm text-slate-600">
          {range.label} · {range.from} → {range.to}
        </p>
      </header>

      <RangeSelector preset={preset} year={year} from={range.from} to={range.to} years={years} />

      {error && (
        <div className="rounded-lg border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900">
          Could not load invoices for this period: {error}
        </div>
      )}

      <SummaryCards summary={summary} />

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-slate-900">Invoices</h2>
        <InvoiceTable invoices={invoices} shop={shop} summary={summary} />
      </section>

      {/* Export block sits at the bottom, visually separated: it is the end of the
          workflow and it owns its own date range. */}
      <div className="border-t border-slate-300 pt-6">
        <QuickbooksExport
          initialPreset={preset}
          initialYear={year}
          initialFrom={range.from}
          initialTo={range.to}
          initialCount={summary.invoiceCount}
          initialTotal={summary.totalInvoiced}
          years={years}
        />
      </div>
    </div>
  )
}
